# Generated by Django 3.0.8 on 2023-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('idcareer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=90)),
                ('image', models.ImageField(default='null', upload_to='')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
